behaviors:
  SimpleCar:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 64
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
    keep_checkpoints: 5
    checkpoint_interval: 500000
    max_steps: 15000000
    time_horizon: 1000
    summary_freq: 40960
    #init_path: None   # Policy to use for initialization. Can be used to resume learning in a new run using an existing model.
    threaded: false
    
engine_settings:
  width: 84
  height: 84
  time_scale: 75
  target_frame_rate: -1
  no_graphics: true
  
# mlagents-learn config/CarLearner.yaml --run-id ppo_01 --env Builds/MAS2025-Assignment-1 --num-envs 8